# Generated by Django 4.1.2 on 2022-10-15 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.currency', verbose_name='Валюта'),
        ),
    ]
